apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-volumen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-volumen
  template:
    metadata:
      labels:
        app: webapp-volumen
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: html-config